### ISSUE TITLE
Sponsors: Homepage

### ISSUE THREAD

**Issue by grappler** [WPSwitzerland/wordcampbern2017#4]
When using `[sponsors link="website"]` on the [homepage](https://2017.bern.wordcamp.org/wp-admin/post.php?post=387&action=edit) the logos are not shown.

**Comment by markhowellsmead** [comment]
Fixed

**Comment by grappler** [comment]
Thanks, but does not seem to be working for me. Even after clearing the cache.

**Comment by markhowellsmead** [comment]
Browser? OS?

**Comment by grappler** [comment]
Chrome & Firefox Mac OS.

**Comment by markhowellsmead** [comment]
Can't replicate the problem.

**Comment by markhowellsmead** [comment]
Ask others to test please

**Comment by markhowellsmead** [comment]
PS do you mean logs or logos?

**Comment by grappler** [comment]
![image](https://cloud.githubusercontent.com/assets/1785641/26532134/89d477c2-43f9-11e7-9d54-d0e1da6d091f.png)

Could you share a screenshot from you end?

**Comment by grappler** [comment]
I have tested it on a second computer in IE and Edge and in Android Chrome with the same results.

**Comment by markhowellsmead** [comment]
![screen shot 2017-05-29 at 12 11 47](https://cloud.githubusercontent.com/assets/1571592/26548349/07403d8e-4474-11e7-9a95-3465cfbf9ad6.png)

**Comment by markhowellsmead** [comment]
PS https://2017.bern.wordcamp.org/wp-admin/post.php?post=387&action=edit isn't the home page. But that page works too.

![support the wordpress conference in switzerland wordcamp bern](https://cloud.githubusercontent.com/assets/1571592/26548391/4475aeb4-4474-11e7-9042-fbbb9aef5f32.png)

**Comment by grappler** [comment]
The page is used on the homepage. You can see the logos are missing from the homepage. https://2017.bern.wordcamp.org/

**Comment by markhowellsmead** [comment]
That's the page I took a screenshot of this morning. The one without the text is the front page; the one with the text is the detail view. No idea. Will take a look when I can.

**Comment by markhowellsmead** [comment]
![screen shot 2017-05-29 at 22 05 26](https://cloud.githubusercontent.com/assets/1571592/26561041/6e0f2574-44bb-11e7-8688-b3d1af50e191.jpg)
![screen shot 2017-05-29 at 22 07 56](https://cloud.githubusercontent.com/assets/1571592/26561043/6e12c9f4-44bb-11e7-9b9e-7446ed79f9cb.jpg)
![screen shot 2017-05-29 at 22 08 11](https://cloud.githubusercontent.com/assets/1571592/26561042/6e10995e-44bb-11e7-8065-ee36d522f498.jpg)

**Comment by grappler** [comment]
Thanks!
